source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Analytics test application.
target 'testapp' do
  pod 'Firebase/Analytics', '3.1.4'
end
