source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
# AdMob test application.
target 'testapp' do
  pod 'Firebase/AdMob'
  pod 'Firebase/Core', '3.1.6'
end