source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# FCM test application.
target 'testapp' do
  pod 'Firebase/CloudMessaging', '3.1.1'
end
