source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Cloud Storage for Firebase test application.
target 'testapp' do
  pod 'Firebase/Storage', '7.0.0'
  pod 'Firebase/Auth', '7.0.0'
end
