source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!
# GMA test application.
target 'testapp' do
  pod 'Google-Mobile-Ads-SDK', '11.2.0'
  pod 'Firebase/Analytics', '10.25.0'
end
