source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Remote Config test application.
target 'testapp' do
  pod 'Firebase/Analytics', '6.0.0'
  pod 'Firebase/RemoteConfig', '6.0.0'
end
