source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Remote Config test application.
target 'testapp' do
  pod 'Firebase/RemoteConfig'
end
