source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Remote Config test application.
target 'testapp' do
  pod 'Firebase/Core', '4.13.0'
  pod 'Firebase/RemoteConfig', '4.13.0'
end
