source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Invites test application.
target 'testapp' do
  pod 'Firebase/Invites', '3.1.6'
end
