source 'sso://cpdc-eap/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
# Invites test application.
target 'testapp' do
  pod 'Firebase/Core'
  pod 'Firebase/Invites'
end
