source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Realtime Database test application.
target 'testapp' do
  pod 'Firebase/Database', '6.14.0'
  pod 'Firebase/Auth', '6.14.0'
end
