source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
# Firebase Realtime Database test application.
target 'testapp' do
  pod 'Firebase/Database', '10.25.0'
  pod 'Firebase/Auth', '10.25.0'
end
