source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Realtime Database test application.
target 'testapp' do
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
