source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Firestore test application.
target 'testapp' do
  pod 'Firebase/Analytics', '6.18.0'
  pod 'Firebase/Firestore', '6.18.0'
  pod 'Firebase/Auth', '6.18.0'
end
