source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
# Cloud Functions for Firebase test application.
target 'testapp' do
  pod 'Firebase/Functions', '10.25.0'
  pod 'Firebase/Auth', '10.25.0'
end
