source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Cloud Functions for Firebase test application.
target 'testapp' do
  pod 'Firebase/Core', '5.18.0'
  pod 'Firebase/Functions', '5.18.0'
  pod 'Firebase/Auth', '5.18.0'
end
